Repository Astr0clad/minecraftdarkmode, pull requests merged in 2021-01, with the labels that each got.

#57 Update inventory.png
  assets/minecraft/textures/gui/container/inventory.png
Labels: enhancement, high-priority

#58 Updated Crafting Table, Blast Furnace, Furnace, and Hopper UI
  assets/minecraft/textures/gui/container/blast_furnace.png
  assets/minecraft/textures/gui/container/crafting_table.png
  assets/minecraft/textures/gui/container/furnace.png
  assets/minecraft/textures/gui/container/hopper.png
Labels: enhancement, high-priority

#59 connected gold block
  assets/minecraft/models/block/gold_block.json
  assets/minecraft/textures/.DS_Store
  assets/minecraft/textures/block/.DS_Store
  assets/minecraft/textures/block/gold_block_borderless.png
  assets/minecraft/textures/gui/.DS_Store
Labels: enhancement

#65 Update README.md
  README.md
Labels: bug

#82 Add Connected Wool
  assets/.DS_Store
  assets/minecraft/.DS_Store
  assets/minecraft/models/.DS_Store
  assets/minecraft/models/block/black_wool.json
  assets/minecraft/models/block/blue_wool.json
  assets/minecraft/models/block/brown_wool.json
  assets/minecraft/models/block/cyan_wool.json
  assets/minecraft/models/block/gray_wool.json
  assets/minecraft/models/block/green_wool.json
  assets/minecraft/models/block/light_blue_wool.json
  assets/minecraft/models/block/light_gray_wool.json
  assets/minecraft/models/block/lime_wool.json
  assets/minecraft/models/block/magenta_wool.json
  assets/minecraft/models/block/orange_wool.json
  assets/minecraft/models/block/pink_wool.json
  assets/minecraft/models/block/purple_wool.json
  assets/minecraft/models/block/red_wool.json
  assets/minecraft/models/block/white_wool.json
  assets/minecraft/models/block/yellow_wool.json
  assets/minecraft/textures/.DS_Store
  assets/minecraft/textures/block/.DS_Store
  assets/minecraft/textures/block/black_wool.png
  assets/minecraft/textures/block/black_wool_borderless.png
  assets/minecraft/textures/block/blue_wool copy.png
  assets/minecraft/textures/block/blue_wool.png
  assets/minecraft/textures/block/brown_wool.png
  assets/minecraft/textures/block/brown_wool_borderless.png
  assets/minecraft/textures/block/cyan_wool.png
  assets/minecraft/textures/block/cyan_wool_borderless.png
  assets/minecraft/textures/block/gray_wool.png
  assets/minecraft/textures/block/gray_wool_borderless.png
  assets/minecraft/textures/block/green_wool.png
  assets/minecraft/textures/block/green_wool_borderless.png
  assets/minecraft/textures/block/light_blue_wool.png
  assets/minecraft/textures/block/light_blue_wool_borderless.png
  assets/minecraft/textures/block/light_gray_wool.png
  assets/minecraft/textures/block/light_gray_wool_borderless.png
  assets/minecraft/textures/block/lime_wool.png
  assets/minecraft/textures/block/lime_wool_borderless.png
  assets/minecraft/textures/block/magenta_wool.png
  assets/minecraft/textures/block/magenta_wool_borderless.png
  assets/minecraft/textures/block/orange_wool.png
  assets/minecraft/textures/block/orange_wool_borderless.png
  assets/minecraft/textures/block/pink_wool.png
  assets/minecraft/textures/block/pink_wool_borderless.png
  assets/minecraft/textures/block/purple_wool.png
  assets/minecraft/textures/block/purple_wool_borderlesss.png
  assets/minecraft/textures/block/red_wool.png
  assets/minecraft/textures/block/red_wool_borderless.png
  assets/minecraft/textures/block/white_wool.png
  assets/minecraft/textures/block/white_wool_borderless.png
  assets/minecraft/textures/block/yellow_wool.png
  assets/minecraft/textures/block/yellow_wool_borderless.png
Labels: enhancement, high-priority

#85 fix blue wool
  .DS_Store
  assets/minecraft/.DS_Store
  assets/minecraft/models/.DS_Store
  assets/minecraft/textures/.DS_Store
  assets/minecraft/textures/block/blue_wool_borderless.png
Labels: bug, high-priority

#86 update readme
  README.md
Labels: bug, enhancement
